### ISSUE TITLE
建议挪除习题答案部分

### ISSUE THREAD

**Issue by Sakurajyan** [syvshc/2019Fall_FA#105]
学生参考答案的情况比较严重

**Comment by EdmundWhis** [comment]
Thanks for your attention.

The process of independent thinking before looking at the answer is particularly precious. You may not figure it out, may think wrong, or get mad that you can’t do anything about it. But the process, in fact, is actually a process of reviewing and consolidating the existing knowledge, which is extremely important for the study of math.

The next step, after spending enough time on these exercises, should be to compare your thoughts to the ones appeared in the answer reference (if it’s standard and detailed). Try to find a bifurcation between your answer and the reference, or if the reference applies a condition that you have ignored. Read the answer closely and ask yourself repeatedly:

Why did it do this?
How the transformation of the conditions drives the subsequent result?
What role does it play In the final solution?
Why didn’t I think of looking for this result in order to transform this condition?

This is the key. And the answer plays an important role.

Thanks again for your attention and precious suggestions.

Edmund,

26 Oct, 2020.

**Comment by Sakurajyan** [comment]
可以设置成私密仓库，把笔记部分单独创建一个仓库出来么？在release的部分还是能找到历史代码和答案.

**Comment by EdmundWhis** [comment]
Thanks for your suggestion.

I don't think it's necessary.

Edmund,

26 Oct, 2020.
